### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by s-mahesh-kumar** [celalaygar/Hospital-Management-System-React-and-SpringBoot#3]
Following the instructions in documentation leads to error ( In Backend ) which i think is the SQL database management problem or anything related to that which has not been shared in documentation 

![image](https://user-images.githubusercontent.com/77258530/176225850-11a3a327-a8e8-41e0-ab47-e2382b97f1e3.png)
![image](https://user-images.githubusercontent.com/77258530/176225960-89c7070c-e0fb-4f5f-8055-454f09ea300c.png)

**Comment by s-mahesh-kumar** [comment]
Fixed

**Comment by celalaygar** [comment]
We need to use java 1.8 to fix this problem..
